### ISSUE TITLE
about this Framework

### ISSUE THREAD

**Issue by b4lie** [DesertImage/ecs-burst#7]
Hello, I am using your ecs framework. I see that this framework does not require code generation. I would like to ask which ecs this framework is based on or is it developed by you yourself?

**Comment by DesertImage** [comment]
Hi!

I would not recommend you to use my framework right now because it's not production ready yet. And can contains rare bugs. 

It's not base on any other ecs frameworks, but i took inspiration and took few things from https://github.com/chromealex/ME.BECS. It does not require to interact with code generation manually too. Also it has better optimization and some ready to use features (you can find them in chromealex repositories). 

Good luck!

**Comment by yuliuren** [comment]
> Hi!
> 
> I would not recommend you to use my framework right now because it's not production ready yet. And can contains rare bugs.
> 
> It's not base on any other ecs frameworks, but i took inspiration and took few things from https://github.com/chromealex/ME.BECS. It does not require to interact with code generation manually too. Also it has better optimization and some ready to use features (you can find them in chromealex repositories).
> 
> Good luck!

Thank you for your prompt reply.

Yes, I also found that it is indeed not perfect now and lacks some scalable support.

But after comparing many ECS frameworks of the same type, I think your ECS framework is very good in design and is waiting for your improvement.

I'm looking forward to putting it into production.😊
